import * as fs from "fs";
import * as path from "path";

// Load .env.local
const envPath = path.resolve(process.cwd(), ".env.local");
const envContent = fs.readFileSync(envPath, "utf-8");
for (const line of envContent.split("\n")) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const idx = trimmed.indexOf("=");
  if (idx !== -1) {
    const key = trimmed.slice(0, idx).trim();
    const val = trimmed.slice(idx + 1).trim().replace(/(^["']|["']$)/g, "");
    if (!process.env[key]) {
      process.env[key] = val;
    }
  }
}

async function testAcceptance() {
  console.log("=== Acceptance Verification: Rich Content Generation Pipeline ===");
  const { generateBlogPost } = await import("../lib/ai/generateBlogPost");

  const testCases = [
    {
      topic: "B2B SaaS Lead Generation: Performance Marketing Tactics for 2026",
      tone: "Authoritative and Tactical",
      keywords: ["B2B SaaS", "Lead Generation", "CAC", "LinkedIn Ads"],
      wordCount: 600,
      audience: "B2B SaaS Founders and Growth Marketers",
    },
    {
      topic: "E-Commerce SEO Checklist: Dominating Organic Search in India",
      tone: "Practical & Step-by-Step",
      keywords: ["E-Commerce SEO", "Category Pages", "Product Schema", "Organic Traffic"],
      wordCount: 600,
      audience: "D2C Brand Owners",
    },
    {
      topic: "AI-Powered WhatsApp Marketing: Converting Inbound Chats into Loyal Customers",
      tone: "Engaging and Visionary",
      keywords: ["WhatsApp Marketing", "Conversational AI", "Customer Retention", "Conversion Rate"],
      wordCount: 600,
      audience: "Retail Business Owners",
    },
  ];

  let passed = 0;

  for (let i = 0; i < testCases.length; i++) {
    const tc = testCases[i];
    console.log(`\n--- [Test ${i + 1}/${testCases.length}] Topic: "${tc.topic}" ---`);
    const start = Date.now();
    const result = await generateBlogPost(tc);
    const duration = ((Date.now() - start) / 1000).toFixed(1);

    console.log(`Duration: ${duration}s`);
    console.log(`Title: "${result.title}"`);
    console.log(`Meta: "${result.metaDescription}"`);
    console.log(`Tags: [${result.suggestedTags.join(", ")}]`);
    console.log(`HTML Length: ${result.content.length} chars`);

    // Validations
    const hasH2 = /<h2\b[^>]*>/i.test(result.content);
    const hasH3 = /<h3\b[^>]*>/i.test(result.content);
    const hasP = /<p\b[^>]*>/i.test(result.content);
    const hasList = /<(?:ul|ol)\b[^>]*>[\s\S]*?<li\b/i.test(result.content);
    const hasBold = /<strong\b[^>]*>/i.test(result.content);
    const hasBlockquote = /<blockquote\b[^>]*>/i.test(result.content);
    const hasAiLeak = /(?:ChatGPT|OpenAI|Llama|AI language model|generated by ai)/i.test(result.content);

    console.log(`- H2 headings: ${hasH2 ? "✅" : "❌"}`);
    console.log(`- H3 subsections: ${hasH3 ? "✅" : "❌"}`);
    console.log(`- Paragraphs: ${hasP ? "✅" : "❌"}`);
    console.log(`- Lists (ul/ol + li): ${hasList ? "✅" : "❌"}`);
    console.log(`- Bold marks: ${hasBold ? "✅" : "❌"}`);
    console.log(`- Blockquote: ${hasBlockquote ? "✅" : "❌"}`);
    console.log(`- AI leak check (clean): ${!hasAiLeak ? "✅" : "❌"}`);

    if (hasH2 && hasP && hasList && hasBold && !hasAiLeak) {
      console.log(`>>> Test ${i + 1} PASSED!`);
      passed++;
    } else {
      console.error(`>>> Test ${i + 1} FAILED checks!`);
    }

    // Print excerpt
    console.log("Snippet:\n" + result.content.slice(0, 400) + "...\n");
  }

  console.log(`\n========================================`);
  console.log(`Acceptance Summary: ${passed}/${testCases.length} tests passed.`);
  if (passed !== testCases.length) {
    process.exit(1);
  }
}

testAcceptance().catch((err) => {
  console.error("Acceptance test failed:", err);
  process.exit(1);
});
