import * as fs from "fs";
import * as path from "path";

// Load .env.local
const envPath = path.resolve(process.cwd(), ".env.local");
const envContent = fs.readFileSync(envPath, "utf-8");
for (const line of envContent.split("\n")) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const idx = trimmed.indexOf("=");
  if (idx !== -1) {
    const key = trimmed.slice(0, idx).trim();
    const val = trimmed.slice(idx + 1).trim().replace(/(^["']|["']$)/g, "");
    if (!process.env[key]) {
      process.env[key] = val;
    }
  }
}

async function testAI() {
  console.log("--- Testing AI Generation Layer (/lib/ai/generateBlogPost.ts) ---");
  console.log("AI_PROVIDER:", process.env.AI_PROVIDER || "groq");
  console.log("GROQ_API_KEY present:", Boolean(process.env.GROQ_API_KEY));

  const { generateBlogPost } = await import("../lib/ai/generateBlogPost");

  try {
    const result = await generateBlogPost({
      topic: "Top 5 Local SEO Strategies for Indian Agencies",
      tone: "Professional & Authoritative",
      keywords: ["Local SEO", "Google My Business", "Organic Ranking"],
      wordCount: 500,
      audience: "Marketing executives and agency owners",
    });

    console.log("✅ AI Generation Succeeded!");
    console.log("Title:", result.title);
    console.log("Meta Description:", result.metaDescription);
    console.log("Suggested Tags:", result.suggestedTags);
    console.log("Content Length (HTML chars):", result.content.length);
    console.log("--- SAMPLE CONTENT START ---");
    console.log(result.content.slice(0, 1500));
    console.log("--- SAMPLE CONTENT END ---");

    // Validate structure
    if (!result.title || !result.content || !Array.isArray(result.suggestedTags)) {
      throw new Error("AI output missing required fields");
    }

    // Validate guardrails: No AI badge in HTML
    if (result.content.includes("Generated by AI") || result.content.includes("AI model") || result.content.includes("ChatGPT") || result.content.includes("Llama")) {
      console.error("❌ CRITICAL: Fingerprints found in AI content!");
      process.exit(1);
    }

    console.log("✅ Content guardrail verified: No AI badges or generator fingerprints found in HTML.");
    console.log("--- Step 7 AI Generation Test Complete! ---");
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("❌ AI Generation Failed:", message);
    process.exit(1);
  }
}

testAI();
